Repository egg-system/borderless-gym, pull requests merged in 2020-07, with the labels that each got.

#75 AWSのECRへのイメージをpushする
  .circleci/config.yml
  nginx/Dockerfile
  php-fpm/prod.dockerfile
Labels: WANT, エンハンスメント

#80 ルートの整理
  .circleci/config.yml
  src/app/Http/Middleware/Authenticate.php
  src/resources/views/common/_loginForm.blade.php
  src/resources/views/layouts/header.blade.php
  src/routes/api.php
  src/routes/web.php
Labels: WANT, 環境整備

#82 composerのスクリプトを、開発モードかどうかで分岐させる
  .circleci/config.yml
  src/composer.json
Labels: MUST, 環境整備

#79 デプロイ時にビルドコマンドを実行する
  .circleci/config.yml
  php-fpm/build.sh
  php-fpm/prod.dockerfile
Labels: WANT, 環境整備

#83 本番環境が立ち上がらない
  php-fpm/build.sh
Labels: MUST, 環境整備

#86 storybookの導入
  src/.storybook/config.js
  src/.storybook/webpack.config.js
  src/package-lock.json
  src/package.json
  src/resources/js/components/ExampleComponent.stories.js
  src/resources/views/sample.blade.php
Labels: WANT, 環境整備

#87 readmeにstorybookの詳細を記載
  README.md
Labels: WANT, 環境整備

#93 readmeの体裁を整える
  .github/issue_template.md
  README.md
  docs/design-rules.md
Labels: WANT, リファクタリング

#96 vuetifyの導入
  .circleci/config.yml
  src/.gitignore
  src/package-lock.json
  src/package.json
  src/resources/js/app.js
  src/resources/js/organisms/app-slot.vue
  src/resources/js/plugins/vuetify.js
  src/resources/sass/app.scss
  src/resources/scss/app.scss
  src/resources/scss/base.scss
  src/resources/scss/landing-page.scss
  src/resources/views/components/layouts/app/head.blade.php
  src/resources/views/components/layouts/common/app.blade.php
  src/resources/views/components/layouts/common/head.blade.php
  src/resources/views/components/layouts/common/header.blade.php
  src/resources/views/components/layouts/common/script.blade.php
  src/resources/views/components/layouts/common/sidebar.blade.php
  src/resources/views/components/layouts/landing-page/head.blade.php
  src/resources/views/components/layouts/landing-page/header.blade.php
  src/resources/views/components/layouts/script.blade.php
  src/resources/views/pages/landing.blade.php
  src/resources/views/templates/app.blade.php
  src/resources/views/templates/base.blade.php
  src/resources/views/templates/landing-page.blade.php
  src/webpack.mix.js
Labels: MUST, デザイン

#97 ビルドしたjsもあわせてデプロイする
  .circleci/config.yml
Labels: MUST, デザイン, バグ, 環境整備

#84 #60 ユーザー関連のServiceクラスをRepositoryへ移植するリファクタリング
  src/app/Http/Controllers/Auth/LoginController.php
  src/app/Http/Controllers/GymsController.php
  src/app/Http/Controllers/TrainersController.php
  src/app/Http/Controllers/UsersController.php
  src/app/Http/Requests/Trainer/UpdateRequest.php
  src/app/Http/Requests/User/RegisterRequest.php
  src/app/Http/Requests/User/UpdateRequest.php
  src/app/Models/Gym.php
  src/app/Models/Login.php
  src/app/Models/Trainer.php
  src/app/Models/User.php
  src/app/Providers/AppServiceProvider.php
  src/app/Providers/RouteServiceProvider.php
  src/app/Repositories/UserRepository.php
  src/app/Services/AuthService.php
  src/resources/views/pages/gyms/edit.blade.php
  src/resources/views/pages/trainers/edit.blade.php
  src/routes/web.php
  src/tests/Feature/LoginTest.php
Labels: WANT, リファクタリング

#103 #91 #95 #101 ユーザー処理関連修正
  src/app/Http/Controllers/Auth/LoginController.php
  src/app/Http/Controllers/UsersController.php
  src/app/Http/Requests/User/RegisterRequest.php
  src/app/Providers/AppServiceProvider.php
  src/app/Providers/ViewServiceProvider.php
  src/resources/views/pages/gyms/edit.blade.php
  src/resources/views/pages/gyms/login.blade.php
  src/resources/views/pages/trainers/edit.blade.php
  src/resources/views/pages/trainers/login.blade.php
  src/resources/views/pages/users/edit.blade.php
  src/resources/views/pages/users/login.blade.php
  src/resources/views/pages/users/register.blade.php
  src/routes/web.php
Labels: WANT, リファクタリング

#113 jsのキャッシュ機構の修正
  .circleci/config.yml
Labels: MUST, デザイン, バグ

#114 ciの修正
  .circleci/config.yml
Labels: MUST, バグ

#116 LPの残コンテンツの実装対応
  src/public/images/landing-page/icon-menu.png
  src/public/images/landing-page/icon-question.png
  src/public/images/landing-page/job-background.png
  src/public/images/landing-page/side-job-background.png
  src/resources/js/atoms/landing-page/content-line.vue
  src/resources/js/atoms/landing-page/descriptions/side-job-description.vue
  src/resources/js/atoms/landing-page/login-btn.vue
  src/resources/js/atoms/landing-page/nav-icon.vue
  src/resources/js/atoms/landing-page/question-icon.vue
  src/resources/js/moleclues/landing-page/feature-descriptions.vue
  src/resources/js/moleclues/landing-page/mian-view.vue
  src/resources/js/moleclues/landing-page/often-question.vue
  src/resources/js/organisms/landing-page/conversion.vue
  src/resources/js/organisms/landing-page/header.vue
  src/resources/js/organisms/landing-page/often-questions.vue
  src/resources/js/organisms/landing-page/question-constants.js
  src/resources/js/plugins/register-components.js
  src/resources/scss/landing-page.scss
  src/resources/views/pages/landing.blade.php
Labels: MUST, デザイン

#119 LPのフッターを実装
  src/resources/js/app.js
  src/resources/js/atoms/landing-page/footer/social-icon.vue
  src/resources/js/atoms/landing-page/nav-icon.vue
  src/resources/js/moleclues/landing-page/footer/menus.vue
  src/resources/js/moleclues/landing-page/footer/social-constants.js
  src/resources/js/moleclues/landing-page/footer/social-icons.vue
  src/resources/js/organisms/landing-page/footer.vue
  src/resources/js/plugins/components/landing-page-components.js
  src/resources/js/plugins/register-components.js
  src/resources/views/pages/landing.blade.php
Labels: MUST, デザイン

#121 キャッシュキーの指定方法を変更
  .circleci/config.yml
Labels: MUST, バグ

#124 LPのデザイン調整
  src/resources/js/atoms/landing-page/login-btn.vue
  src/resources/js/moleclues/landing-page/features-constants.js
  src/resources/js/moleclues/landing-page/footer/menus.vue
  src/resources/js/moleclues/landing-page/nav-menus.vue
  src/resources/js/moleclues/landing-page/often-question.vue
  src/resources/js/organisms/landing-page/often-questions.vue
  src/resources/scss/landing-page.scss
  src/resources/views/pages/landing.blade.php
Labels: MUST, デザイン

#125 文字サイズの微調整
  src/resources/scss/landing-page.scss
Labels: MUST, デザイン

#126 LPの最終調整
  src/resources/js/moleclues/landing-page/footer/social-constants.js
  src/resources/js/moleclues/landing-page/mian-view.vue
Labels: MUST, デザイン

#134 メタタグなどの修正
  src/public/favicon.ico
  src/resources/views/components/layouts/app/head.blade.php
  src/resources/views/components/layouts/common/meta.blade.php
  src/resources/views/components/layouts/landing-page/head.blade.php
  src/resources/views/templates/base.blade.php
Labels: MUST, エンハンスメント

#135 バージョニングを追加
  src/resources/views/components/layouts/landing-page/head.blade.php
  src/webpack.mix.js
Labels: MUST, エンハンスメント

#140 GTMタグの埋め込み
  src/app/Providers/ViewServiceProvider.php
  src/resources/views/components/gtm/body.blade.php
  src/resources/views/components/gtm/head.blade.php
  src/resources/views/templates/base.blade.php
Labels: MUST, エンハンスメント

#142 環境変数envの整理
  .circleci/config.yml
  README.md
  docs/envs.md
  src/database/seeds/CommonSeeder.php
  src/database/seeds/DatabaseSeeder.php
  src/database/seeds/TestingSeeder.php
Labels: WANT, 環境整備

#98 ユーザー編集画面のデザイン実装
  src/.gitignore
  src/app/Repositories/UserRepository.php
  src/package.json
  src/resources/js/molecules/form/form-wrapper.vue
  src/resources/js/molecules/form/input-form.stories.js
  src/resources/js/molecules/form/input-form.vue
  src/resources/js/molecules/form/range-input-form.stories.js
  src/resources/js/molecules/form/range-input-form.vue
  src/resources/js/molecules/form/select-form.stories.js
  src/resources/js/molecules/form/select-form.vue
  src/resources/js/molecules/form/text-area-form.stories.js
  src/resources/js/molecules/form/text-area-form.vue
  src/resources/js/molecules/landing-page/feature-descriptions.vue
  src/resources/js/molecules/landing-page/features-constants.js
  src/resources/js/molecules/landing-page/footer/menus.vue
  src/resources/js/molecules/landing-page/footer/social-constants.js
  src/resources/js/molecules/landing-page/footer/social-icons.vue
  src/resources/js/molecules/landing-page/mian-view.vue
  src/resources/js/molecules/landing-page/nav-menus.vue
  src/resources/js/molecules/landing-page/often-question.vue
  src/resources/js/organisms/landing-page/descriptions.vue
  src/resources/js/organisms/landing-page/first-view.vue
  src/resources/js/organisms/landing-page/footer.vue
  src/resources/js/organisms/landing-page/header.vue
  src/resources/js/organisms/landing-page/often-questions.vue
  src/resources/js/plugins/components/molecules/form-components.js
  src/resources/js/plugins/register-components.js
  src/resources/scss/pages/users/edit.scss
  src/resources/views/components/layouts/app/head.blade.php
  src/resources/views/pages/users/edit.blade.php
  src/webpack.mix.js
Labels: MUST, デザイン

#149 機能のリリース制御機構の実装
  src/app/Providers/ViewServiceProvider.php
  src/config/release.php
  src/package-lock.json
  src/package.json
  src/resources/js/app.js
  src/resources/js/atoms/landing-page/login-btn.vue
  src/resources/js/functional/vue-data-composer.vue
  src/resources/js/molecules/landing-page/nav-menus.vue
  src/resources/js/plugins/register-components.js
  src/resources/js/plugins/store.js
  src/resources/js/stores/release.js
  src/resources/views/components/layouts/common/composer.blade.php
  src/resources/views/templates/base.blade.php
Labels: WANT, エンハンスメント
