Repository egg-system/borderless-gym, pull requests merged in 2020-08, with the labels that each got.

#154 ログインボタンの機能組み込み
  src/package-lock.json
  src/package.json
  src/resources/js/atoms/main-btn.vue
  src/resources/js/molecules/landing-page/login-btn.vue
  src/resources/js/molecules/landing-page/nav-menus.vue
  src/resources/js/organisms/landing-page/conversion.vue
  src/resources/js/organisms/landing-page/first-view.vue
  src/resources/js/organisms/landing-page/header.vue
  src/resources/js/organisms/landing-page/login-dialog.vue
  src/resources/views/components/common/_loginForm.blade.php
  src/resources/views/components/layouts/landing-page/header.blade.php
  src/resources/views/pages/landing.blade.php
  src/resources/views/pages/users/login.blade.php
  src/routes/web.php
Labels: MUST, エンハンスメント, デザイン

#159 リリース制御用のミドルウェアを追加
  src/app/Http/Kernel.php
  src/app/Http/Middleware/CheckIsEnableRoute.php
  src/config/release.php
  src/routes/web.php
Labels: WANT, エンハンスメント

#158 リリース制御用のmdを追加
  README.md
  docs/release.md
Labels: WANT, エンハンスメント

#161 ログの設定を修正
  src/.env.example
  src/app/Http/Kernel.php
  src/app/Http/Middleware/RequestLogger.php
  src/app/Providers/AppServiceProvider.php
  src/config/logging.php
Labels: WANT, 環境整備

#164 LoginControllerの修正
  .circleci/config.yml
  src/app/Http/Controllers/Auth/LoginController.php
  src/app/Http/Requests/LoginRequest.php
  src/app/Models/Login.php
  src/resources/views/components/common/_loginForm.blade.php
  src/tests/Feature/LoginTest.php
Labels: WANT, バグ

#167 ログイン用のルートを整理する
  docs/release.md
  src/app/Http/Middleware/CheckIsEnableRoute.php
  src/config/release.php
  src/resources/views/components/common/_loginForm.blade.php
  src/resources/views/components/layouts/common/header.blade.php
  src/resources/views/components/layouts/landing-page/header.blade.php
  src/resources/views/pages/auth/login.blade.php
  src/resources/views/pages/auth/passwords/confirm.blade.php
  src/resources/views/pages/auth/passwords/email.blade.php
  src/resources/views/pages/auth/passwords/reset.blade.php
  src/resources/views/pages/auth/register.blade.php
  src/resources/views/pages/auth/verify.blade.php
  src/resources/views/pages/users/login.blade.php
  src/routes/web.php
  src/tests/Feature/LoginTest.php
  src/tests/Feature/TrainerRegisterTest.php
Labels: WANT, リファクタリング

#170 ログインと登録の機能制御を分割する
  src/config/release.php
  src/resources/js/molecules/landing-page/login-btn.vue
  src/routes/web.php
  src/tests/Feature/TrainerRegisterTest.php
Labels: MUST, エンハンスメント

#171 #61 migrationリワーク
  src/database/migrations/2020_07_30_132236_change_column_offers_table.php
  src/database/migrations/2020_07_30_165714_add_column_offer_states.php
  src/database/seeds/testing/OfferStateSeeder.php
Labels: MUST, エンハンスメント

#148 #120 利用規約、プライバシーポリシー、特商法の表記ページを追加
  src/resources/scss/pages/commercial-transactions.scss
  src/resources/scss/pages/privacy-policy.scss
  src/resources/scss/pages/service-term.scss
  src/resources/views/pages/commercial-transactions.blade.php
  src/resources/views/pages/landing.blade.php
  src/resources/views/pages/privacy-policy.blade.php
  src/resources/views/pages/service-term.blade.php
  src/resources/views/templates/landing-page.blade.php
  src/routes/web.php
Labels: MUST, エンハンスメント

#175 ログインボタンと登録ボタンを分割する
  src/app/Http/Controllers/Auth/RegisterController.php
  src/app/Http/Middleware/CheckIsEnableRoute.php
  src/resources/js/atoms/main-btn.vue
  src/resources/js/molecules/landing-page/login-btn.vue
  src/resources/js/molecules/landing-page/register-btn.vue
  src/resources/js/organisms/landing-page/conversion.vue
  src/resources/js/organisms/landing-page/first-view.vue
  src/resources/js/organisms/landing-page/login-area.vue
  src/resources/js/organisms/landing-page/login-dialog.vue
  src/resources/views/pages/email/input-email.blade.php
  src/resources/views/pages/email/send-email.blade.php
  src/resources/views/pages/terms/commercial-transactions.blade.php
  src/resources/views/pages/terms/privacy-policy.blade.php
  src/resources/views/pages/terms/service-term.blade.php
  src/routes/web.php
Labels: MUST, エンハンスメント

#179 ハンバーガーメニューの内容をfix版にする
  src/resources/views/components/layouts/landing-page/header.blade.php
Labels: MUST, エンハンスメント

#173 #61 オファー一覧取得処理修正
  src/app/Http/Requests/Offer/StoreRequest.php
  src/app/Models/Offer.php
  src/app/Services/MatchingService.php
  src/database/migrations/2020_07_30_132236_change_column_offers_table.php
  src/database/migrations/2020_07_30_132252_drop_column_offers_table.php
  src/resources/views/components/offers/listTable.blade.php
Labels: MUST, エンハンスメント

#180 ホーム画面の実装
  src/app/Http/Controllers/Auth/LoginController.php
  src/app/Http/Controllers/GymsController.php
  src/app/Http/Controllers/TrainersController.php
  src/app/Http/Middleware/Authenticate.php
  src/app/Http/Middleware/RedirectIfAuthenticated.php
  src/app/Http/Requests/Auth/RegisterRequest.php
  src/app/Http/Requests/TrainerSearchRequest.php
  src/app/Models/Login.php
  src/app/Providers/ViewServiceProvider.php
  src/resources/js/app.js
  src/resources/js/atoms/app/logout-list-item.vue
  src/resources/js/atoms/app/profile-icon.vue
  src/resources/js/atoms/main-icon.vue
  src/resources/js/molecules/app/header/header-menus.vue
  src/resources/js/molecules/app/header/profile-menu-list.vue
  src/resources/js/molecules/app/header/profile-menus.vue
  src/resources/js/organisms/app/header.vue
  src/resources/js/plugins/register-components.js
  src/resources/views/components/layouts/app/head.blade.php
  src/resources/views/components/layouts/app/header.blade.php
  src/resources/views/components/layouts/common/head.blade.php
  src/resources/views/components/layouts/common/header.blade.php
  src/resources/views/components/layouts/common/sidebar.blade.php
  src/resources/views/components/layouts/landing-page/head.blade.php
  src/resources/views/pages/email/input-email.blade.php
  src/resources/views/pages/email/send-email.blade.php
  src/resources/views/pages/trainers/index.blade.php
  src/resources/views/pages/users/login.blade.php
  src/resources/views/pages/users/register.blade.php
  src/resources/views/templates/app.blade.php
  src/routes/web.php
  src/tests/Feature/GymOwnerTest.php
Labels: MUST, エンハンスメント

#184 cacheのkeyにブランチもつける
  .circleci/config.yml
Labels: MUST, バグ, 環境整備

#193 デザイン崩れの修正
  src/resources/js/atoms/landing-page/footer/social-icon.vue
  src/resources/js/atoms/landing-page/main-image.vue
  src/resources/js/atoms/landing-page/nav-icon.vue
  src/resources/js/atoms/main-btn.vue
  src/resources/js/molecules/landing-page/descriptions/feature-description.vue
  src/resources/js/molecules/landing-page/descriptions/service-description.vue
  src/resources/js/molecules/landing-page/descriptions/side-job-description.vue
  src/resources/js/molecules/landing-page/feature-descriptions.vue
  src/resources/js/molecules/landing-page/footer/menus.vue
  src/resources/js/molecules/landing-page/footer/social-icons.vue
  src/resources/js/molecules/landing-page/mian-view.vue
  src/resources/js/molecules/landing-page/nav-menus.vue
  src/resources/js/molecules/landing-page/often-question.vue
  src/resources/js/organisms/landing-page/conversion.vue
  src/resources/js/organisms/landing-page/descriptions.vue
  src/resources/js/organisms/landing-page/first-view.vue
  src/resources/js/organisms/landing-page/footer.vue
  src/resources/js/organisms/landing-page/header.vue
  src/resources/js/organisms/landing-page/login-area.vue
  src/resources/js/organisms/landing-page/often-questions.vue
  src/resources/scss/_variables.scss
  src/resources/scss/landing-page.scss
Labels: MUST, デザイン, バグ

#203 パスワードリセットの機能実装
  src/app/Http/Controllers/Auth/ConfirmPasswordController.php
  src/app/Http/Controllers/Auth/ForgotPasswordController.php
  src/app/Http/Controllers/Auth/ResetPasswordController.php
  src/app/Http/Controllers/Auth/VerificationController.php
  src/app/Providers/AppServiceProvider.php
  src/resources/views/auth/passwords/email-sent.blade.php
  src/resources/views/auth/passwords/email.blade.php
  src/resources/views/auth/passwords/reset.blade.php
  src/routes/web.php
Labels: MUST, エンハンスメント

#204 プロフィール編集画面のルート整理
  src/app/Http/Controllers/UsersController.php
  src/app/Http/Requests/TrainerSearchRequest.php
  src/app/Providers/AuthServiceProvider.php
  src/resources/views/components/common/_form.blade.php
  src/resources/views/components/common/_loginForm.blade.php
  src/resources/views/components/common/modal.blade.php
  src/resources/views/components/layouts/app/header.blade.php
  src/resources/views/pages/users/edit.blade.php
  src/routes/web.php
Labels: MUST, リファクタリング

#131 #61 オファー周り整理
  src/app/Http/Controllers/OffersController.php
  src/app/Http/Requests/Offer/StoreRequest.php
  src/app/Http/Requests/Offer/UpdateRequest.php
  src/app/Mail/OfferUpdate.php
  src/app/Models/Login.php
  src/app/Models/Offer.php
  src/app/Notifications/OfferNotify.php
  src/app/Observers/OfferObserver.php
  src/app/Policies/OfferPolicy.php
  src/app/Providers/ViewServiceProvider.php
  src/database/migrations/2020_07_30_132236_change_column_offers_table.php
  src/database/migrations/2020_07_30_132252_drop_column_offers_table.php
  src/resources/views/components/offers/listTable.blade.php
  src/resources/views/pages/offers/show.blade.php
  src/routes/web.php
Labels: MUST, エンハンスメント

#211 テストが通るようにする
  src/app/Models/MatchingCondition.php
  src/app/Repositories/UserRepository.php
  src/tests/Feature/TrainerRegisterTest.php
Labels: MUST, バグ

#213 ログイン後のグローバルヘッダーを実装
  src/app/Models/Login.php
  src/public/images/app/home-icon-active.png
  src/public/images/app/home-icon.png
  src/public/images/app/message-icon-active.png
  src/public/images/app/message-icon.png
  src/public/images/app/setting-icon-active.png
  src/public/images/app/setting-icon.png
  src/resources/js/atoms/app/header/header-menu.vue
  src/resources/js/atoms/app/header/image-icon.vue
  src/resources/js/atoms/app/header/logout-list-item.vue
  src/resources/js/atoms/app/profile-icon.vue
  src/resources/js/molecules/app/header/header-menus.vue
  src/resources/js/molecules/app/header/profile-menu-list.vue
  src/resources/js/molecules/app/header/profile-menus.vue
  src/resources/js/organisms/app/header.vue
  src/resources/scss/app.scss
  src/resources/views/components/layouts/app/header.blade.php
  src/resources/views/pages/users/edit.blade.php
  src/routes/web.php
  src/tests/Feature/GymOwnerTest.php
Labels: MUST, デザイン

#220 マスターのテストが落ちる
  src/tests/Feature/TrainerOwnerTest.php
  src/tests/Feature/UserSearchServiceTest.php
Labels: MUST, バグ

#223 主要モデルの一覧と詳細を実装
  src/app/Http/Clients/HeartRailsExpressClient.php
  src/app/Http/Controllers/GymsController.php
  src/app/Http/Controllers/TrainersController.php
  src/app/Models/Gym.php
  src/app/Models/Job.php
  src/app/Models/MatchingCondition.php
  src/app/Models/Occupation.php
  src/app/Models/Trainer.php
  src/app/Models/UserOccupation.php
  src/app/Policies/GymPolicy.php
  src/app/Policies/TrainerPolicy.php
  src/app/Providers/AuthServiceProvider.php
  src/app/Repositories/UserRepository.php
  src/database/factories/GymFactory.php
  src/database/factories/JobFactory.php
  src/database/factories/MatchingConditionFactory.php
  src/database/factories/TrainerFactory.php
  src/database/migrations/2020_07_18_145538_change_column_matching_conditions_table.php
  src/database/migrations/2020_08_17_231723_alter_job_content_table.php
  src/database/migrations/2020_08_18_021720_alter_foreign_key_occupations_table.php
  src/database/migrations/2020_08_18_025827_alter_carrer_traienrs_table.php
  src/database/seeds/TestingSeeder.php
  src/database/seeds/testing/JobsTableSeeder.php
  src/public/images/trainers/trainer-icon.png
  src/resources/js/plugins/components/landing-page-components.js
  src/resources/js/plugins/register-components.js
  src/resources/scss/app.scss
  src/resources/scss/pages/gyms/index.scss
  src/resources/scss/pages/gyms/show.scss
  src/resources/scss/pages/trainers/index.scss
  src/resources/scss/pages/trainers/show.scss
  src/resources/views/components/layouts/app/header.blade.php
  src/resources/views/components/layouts/common/footer.blade.php
  src/resources/views/pages/gyms/index.blade.php
  src/resources/views/pages/gyms/show.blade.php
  src/resources/views/pages/terms/commercial-transactions.blade.php
  src/resources/views/pages/terms/privacy-policy.blade.php
  src/resources/views/pages/terms/service-term.blade.php
  src/resources/views/pages/trainers/index.blade.php
  src/resources/views/pages/trainers/show.blade.php
  src/resources/views/templates/base.blade.php
  src/routes/web.php
  src/tests/Feature/GymOwnerTest.php
  src/tests/Feature/TrainerOwnerTest.php
  src/tests/Feature/TrainerRegisterTest.php
Labels: MUST, エンハンスメント, デザイン, バグ

#224 マスターのテストが落ちる
  src/app/Http/Requests/GymSearchRequest.php
  src/app/Models/Job.php
  src/app/Models/MatchingCondition.php
  src/app/Models/Occupation.php
  src/app/Models/Trainer.php
  src/public/images/users-register/gym_trainer_icon.jpg
  src/resources/js/organisms/users-register/name-step.vue
  src/tests/Feature/TrainerRegisterTest.php
Labels: MUST, デザイン, バグ

#234 ジムを登録するコマンドの追加
  src/app/Console/Commands/GymCreateCommand.php
Labels: MUST, エンハンスメント, バグ

#236 経歴が表示出来ないバグの修正
  src/app/Models/Login.php
  src/app/Repositories/UserRepository.php
  src/resources/views/pages/users/edit.blade.php
Labels: MUST, エンハンスメント, バグ

#239 会員登録メールの署名付きアドレスが無効と言われる
  src/app/Http/Middleware/TrustProxies.php
Labels: MUST, バグ

#240 ジム登録コマンドの結果にgym_idも表示する
  src/app/Console/Commands/GymCreateCommand.php
  src/database/seeds/CommonSeeder.php
  src/database/seeds/TestingSeeder.php
  src/database/seeds/common/AreasTableSeeder.php
  src/database/seeds/common/OfferStateSeeder.php
Labels: WANT, エンハンスメント

#243 α版のデザイン指摘事項の対応
  src/app/Repositories/UserRepository.php
  src/resources/js/molecules/landing-page/footer/social-icons.vue
  src/resources/js/organisms/landing-page/login-area.vue
  src/resources/js/organisms/users-register/area-step.vue
  src/resources/js/organisms/users-register/name-step.vue
  src/resources/js/organisms/users-register/password-step.vue
  src/resources/views/components/layouts/common/head.blade.php
  src/resources/views/pages/email/input-email.blade.php
  src/resources/views/pages/gyms/show.blade.php
  src/resources/views/pages/users/login.blade.php
Labels: MUST, デザイン, バグ

#244 #105 SCSSのベンダープリフィックスを自動でつける
  src/package.json
Labels: WANT, エンハンスメント
